spring.application.name=spreenboot

# Conexión a MongoDB (Local)
# mongodb://[host]:[puerto]/[nombre_de_la_bd]
spring.mongodb.uri=mongodb://localhost:27017/parcialsw1
# Muestra por qué se deniega el acceso
logging.level.org.springframework.security=DEBUG
# Muestra qué filtros se están ejecutando
logging.level.org.springframework.web.filter=DEBUG
# Mostrar los comandos que Spring ejecuta en la consola (útil para debug)
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
# Aumentar el límite de tamaño para archivos (Audios de voz)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# URL de tu servidor FastAPI (opcional, para no ponerla a fuego en el código)
ia.fastapi.url=http://localhost:8000